name: Codecov

on:
  push:
    branches: [master]

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - name: Install Dependencies
        run: npm install
      - name: Run cover
        run: npm cover
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
